name: CI/CD
on:
  push:  #kích hoạt khi push code 
    branches: [master]    

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master       #ktra code
      - name: Build Docker
        run: docker compose up --build -d       #start các container

